### ISSUE TITLE
 does not show double quotes at the beginning and end of the line

### ISSUE THREAD

**Issue by ltahuite** [jmviz/quote-list#4]
INSURER_SLUG,POLICY_NUMBER, MINIMUM_TOTAL_AMOUNT, COPAYMENT_AMOUNT,COINSURANCE_PERCENTAGE
gt,15212,600,100,15
gt,55152,500,100,15
gt,55259,600,100,15
gt,55273,660,100,15

after ctrl+shift+'

"INSURER_SLUG","POLICY_NUMBER", "MINIMUM_TOTAL_AMOUNT", "COPAYMENT_AMOUNT","COINSURANCE_PERCENTAGE
gt","15212","600","100","15
gt","55152","500","100","15
gt","55259","600","100","15
gt","55273","660","100","15"

**Comment by jmviz** [comment]
This is working as expected since there are no trailing commas at the end of the lines to separate the last entry in one line from the first entry in the next. One way to do what you want would be to do a multi-cursor select on each line and then use the quote list command, so that it applies to each line individually: select all, then alt+shift+i (put a cursor at the end of each line), then ctrl+l (select the whole of each line), then ctrl+shift+'.
